insert into `t_items` value ("","GIFT","","禮物","null","100","","PDT","","","");
insert into `t_items` value ("","GUS0120","Gel Urinal Screen","香味尿格","null","10","","PDT","","","");
insert into `t_items` value ("","Pentax","","Pentax 水泵","null","1100","","PDT","","","");
insert into `t_items` value ("","DA0110","Graese Trap Cleaner","Drain Away 隔油池化油劑","null","328","","PDT","","","");
insert into `t_items` value ("","DA0205","Graese Trap Cleaner","Drain Away 隔油池化油劑","null","340","","PDT","","","");
insert into `t_items` value ("","DA0405","Graese Trap Cleaner","Drain Away 隔油池化油劑","null","0","","PDT","","","");
insert into `t_items` value ("","DD0120","Dishmachine Detergent","DD-100 洗碗碟機鹼液","null","80","","PDT","","","");
insert into `t_items` value ("","DD0405","Dishmachine Detergent","DD-100 洗碗碟機鹼液","null","120","","PDT","","","");
insert into `t_items` value ("","DF0105","Concentrated Dishwasher Drying Agent","Dry Flash 高濃縮洗碗碟機快乾劑","null","45","","PDT","","","");
insert into `t_items` value ("","DF0120","Concentrated Dishwasher Drying Agent","Dry F lash 高濃縮洗碗碟機快乾劑","null","180","","PDT","","","");
insert into `t_items` value ("","DF0205","Concentrated Dishwasher Drying Agent","Dry Flash 高濃縮洗碗碟機快乾劑","null","90","","PDT","","","");
insert into `t_items` value ("","DF0405","Concentrated Dishwasher Drying Agent","Dry Flash 高濃縮洗碗碟機快乾劑","null","180","","PDT","","","");
insert into `t_items` value ("","DM0104","Concentrated Oxygenic Stain Remover","Dip Master 高濃縮活氧浸漬粉","null","80","","PDT","","","");
insert into `t_items` value ("","DM0105","Concentrated Oxygenic Stain Remover","Dip Master 高濃縮活氧浸漬粉","null","80","","PDT","","","");
insert into `t_items` value ("","DM0205","Concentrated Oxygenic Stain Remover","Dip Master 高濃縮活氧浸漬粉","null","150","","PDT","","","");
insert into `t_items` value ("","DM0404","Concentrated Oxygenic Stain Remover","Dip Master 高濃縮活氧浸漬粉","null","310","","PDT","","","");
insert into `t_items` value ("","DM0405","Concentrated Oxygenic Stain Remover","Dip Master 高濃縮活氧浸漬粉","null","310","","PDT","","","");
insert into `t_items` value ("","DR0120","Dishmachine Rinse Agent","DR-100 洗碗碟機催乾劑","null","130","","PDT","","","");
insert into `t_items` value ("","DR0405","Dishmachine Rinse Agent","DR-100 洗碗碟機催乾劑","null","160","","PDT","","","");
insert into `t_items` value ("","EC0112","Easy Clean","易潔","null","200","","PDT","","","");
insert into `t_items` value ("","EP0405","Electrostatic Precipitation System Degreaser","EP Cleaner 靜電油煙系統除油劑","null","110","","PDT","","","");
insert into `t_items` value ("","EWP0204","High Concentrated Multi-Purpose Cleaner","Easy Wash Plus 超濃縮全能清潔劑","null","65","","PDT","","","");
insert into `t_items` value ("","EWP0404","High Concentrated Multi-Purpose Cleaner","Easy Wash Plus 超濃縮全能清潔劑","null","130","","PDT","","","");
insert into `t_items` value ("","F160205","Chlorinated Floor Cleaner","F-16 高濃縮氯性地面清潔劑","null","67","","PDT","","","");
insert into `t_items` value ("","F160405","Chlorinated Floor Cleaner","F-16 高濃縮氯性地面清潔劑","null","138","","PDT","","","");
insert into `t_items` value ("","FC0405","Kitchen Floor Cleaner","FC-100 廚房地板清潔劑","null","140","","PDT","","","");
insert into `t_items` value ("","GD0405","Grill Degreaser","爐具清潔劑","null","340","","PDT","","","");
insert into `t_items` value ("","GD-P","High Concentrated Grill Degreaser","GD-Plus 超濃縮扒爐水","null","170","","PDT","","","");
insert into `t_items` value ("","GDP0401","High Concentrated Grill Degreaser","GD-Plus 超濃縮扒爐水","null","300","","PDT","","","");
insert into `t_items` value ("","GDP0405","High Concentrated Grill Degreaser","GD-Plus 超濃縮爐具清潔劑","null","300","","PDT","","","");
insert into `t_items` value ("","GR0205","Heavy Duty Degreaser","Grease Remover 強力爐灶除油劑 ","null","123","","PDT","","","");
insert into `t_items` value ("","GR0401","Heavy Duty Degreaser","Grease Remover 強力爐灶除油劑 ","null","169","","PDT","","","");
insert into `t_items` value ("","GR0405","Heavy Duty Degreaser","Grease Remover 強力爐灶除油劑 ","null","251","","PDT","","","");
insert into `t_items` value ("","GT0110","Grease Trap Degreaser","GT-100 隔油池化油劑","null","330","","PDT","","","");
insert into `t_items` value ("","GT0205","Grease Trap Degreaser","GT-100 隔油池化油劑","null","340","","PDT","","","");
insert into `t_items` value ("","GT0405","Grease Trap Degreaser","GT-100 隔油池化油劑","null","680","","PDT","","","");
insert into `t_items` value ("","H10201","Antimicrobial Hand Soap","H-1 消毒洗手皂液","null","60","","PDT","","","");
insert into `t_items` value ("","H10401","Antimicrobial Hand Soap","H-1 消毒洗手皂液 ","null","120","","PDT","","","");
insert into `t_items` value ("","HF0105","Foam Type Hand Soap","H 1 消毒泡沬洗手皂液 ","null","100","","PDT","","","");
insert into `t_items` value ("","HS0401","Hand Soap","洗手液","null","120","","PDT","","","");
insert into `t_items` value ("","HW0405","Hand Washing Cleaner","HW-100 手洗清潔劑","null","190","","PDT","","","");
insert into `t_items` value ("","LR0120","Concentrated Lime Scale Remover","Lime Remover 超高濃縮水垢去除劑","null","200","","PDT","","","");
insert into `t_items` value ("","LR0205","Concentrated Lime Scale Remover","Lime Remover 超高濃縮水垢去除劑","null","120","","PDT","","","");
insert into `t_items` value ("","LR0401","Concentrated Lime Scale Remover","Lime Remover 超高濃縮水垢去除劑","null","245","","PDT","","","");
insert into `t_items` value ("","LR0405","Concentrated Lime Scale Remover","Lime Remover 超高濃縮水垢去除劑","null","245","","PDT","","","");
insert into `t_items` value ("","MFOLD","M-Fold Paper","方型抹手紙 ","null","150.48","","PDT","","","");
insert into `t_items` value ("","MFTB","Micro Fiber  Cloth (Blue)","M - Cloth 微纖布 (藍色)","null","35","","PDT","","","");
insert into `t_items` value ("","MFTG","Micro Fiber  Cloth (Green)","M - Cloth 微纖布(綠色)","null","35","","PDT","","","");
insert into `t_items` value ("","MFTN","Micro Fiber  Cloth (Brown)","M - Cloth 微纖布 (啡色)","null","35","","PDT","","","");
insert into `t_items` value ("","MFTY","Micro Fiber  Cloth (Yellow)","M - Cloth 微纖布 (黃色)","null","35","","PDT","","","");
insert into `t_items` value ("","MP0401","Multi Purposes Cleaner","MP-100 多用途清潔劑","null","110","","PDT","","","");
insert into `t_items` value ("","NC0105","Concentrated Neutral Multi-Purposes Cleaner","NC-360 中性多用途清潔劑","null","0","","PDT","","","");
insert into `t_items` value ("","NC0401","Concentrated Neutral Multi-Purposes Cleaner","NC-360 中性多用途清潔劑","null","109","","PDT","","","");
insert into `t_items` value ("","OC0401","Heavy Duty Degreaser","Oven Cleaner 爐灶除油劑","null","169","","PDT","","","");
insert into `t_items` value ("","OYP0105","Heavy Duty Alkaline Degreaser Powder","OYP 強力鹼性除油粉","null","67.5","","PDT","","","");
insert into `t_items` value ("","OYP0120","Heavy Duty Alkaline Degreaser Powder","OYP 強力鹼性除油粉","null","230","","PDT","","","");
insert into `t_items` value ("","OYP0205","Heavy Duty Alkaline Degreaser Powder","OYP 強力鹼性除油粉","null","140","","PDT","","","");
insert into `t_items` value ("","OYP0405","Heavy Duty Alkaline Degreaser Powder","OYP 強力鹼性除油粉","null","270","","PDT","","","");
insert into `t_items` value ("","PD0105","Concentrated  Heavy Duty Degreaser","Power Degreaser 高濃縮強力爐灶除油劑","null","85","","PDT","","","");
insert into `t_items` value ("","PD0110","Concentrated  Heavy Duty Degreaser","Power Degreaser 高濃縮強力爐灶除油劑 高濃縮強力爐灶除油劑","null","0","","PDT","","","");
insert into `t_items` value ("","PD0205","Concentrated  Heavy Duty Degreaser","Power Degreaser 高濃縮強力爐灶除油劑","null","165","","PDT","","","");
insert into `t_items` value ("","PD0405","Concentrated  Heavy Duty Degreaser","Power Degreaser 高濃縮強力爐灶除油劑","null","335","","PDT","","","");
insert into `t_items` value ("","SC0101","Liquid Stainless Steel Cleaner & Polish","Steel Cleaner 不銹鋼潔亮劑","null","60","","PDT","","","");
insert into `t_items` value ("","SC0401","Liquid Stainless Steel Cleaner & Polish","Steel Cleaner 不銹鋼潔亮劑","null","240","","PDT","","","");
insert into `t_items` value ("","SG0101","Sanitizer Gel","Sanitizer Gel","null","220","","PDT","","","");
insert into `t_items` value ("","SQ0101","Sanitizer","Sani-Q 餐具殺菌消毒劑","null","240","","PDT","","","");
insert into `t_items` value ("","SR0105","Stain Remover","SR-100 浸漬粉","null","80","","PDT","","","");
insert into `t_items` value ("","SS0104","Enzyme Activated Presoak & Silver Detarnisher","Silver Shine 浸銀粉","null","120","","PDT","","","");
insert into `t_items` value ("","SS0105","Enzyme Activated Presoak & Silver Detarnisher","Silver Shine 浸銀粉","null","120","","PDT","","","");
insert into `t_items` value ("","T100205","Concentrated Pot and Pan Cleaner","T-10 高濃縮餐具清潔劑","null","100","","PDT","","","");
insert into `t_items` value ("","T100405","Concentrated Pot and Pan Cleaner","T-10 高濃縮餐具清潔劑","null","190","","PDT","","","");
insert into `t_items` value ("","T50205","Pot and Pan Cleaner","T-5 餐具清潔劑","null","70","","PDT","","","");
insert into `t_items` value ("","T50405","Pot and Pan Cleaner","T-5 餐具清潔劑","null","150","","PDT","","","");
insert into `t_items` value ("","TD0105","Dishwasher Detergent","TD-150 洗碗碟機清潔劑","null","30","","PDT","","","");
insert into `t_items` value ("","TD0120","Dishwasher Detergent","TD-150 洗碗碟機清潔劑","null","90","","PDT","","","");
insert into `t_items` value ("","TD0205","Dishwasher Detergent","TD-150 洗碗碟機清潔劑","null","58","","PDT","","","");
insert into `t_items` value ("","TD0405","Dishwasher Detergent","TD-150 洗碗碟機清潔劑","null","120.01","","PDT","","","");
insert into `t_items` value ("","TR0105","Drying Agent","TR-250 洗碗碟機快乾劑","null","35","","PDT","","","");
insert into `t_items` value ("","TR0120","Drying Agent","TR-250 洗碗碟機快乾劑","null","130","","PDT","","","");
insert into `t_items` value ("","TR0205","Drying Agent","TR-250 洗碗碟機快乾劑","null","80","","PDT","","","");
insert into `t_items` value ("","TR0405","Drying Agent","TR-250 洗碗碟機快乾劑","null","160","","PDT","","","");
insert into `t_items` value ("","TS0105","Concentrated Dishwasher Detergent","Top Shine 高濃縮洗碗碟機清潔劑","null","40","","PDT","","","");
insert into `t_items` value ("","TS0120","Concentrated Dishwasher Detergent","Top Shine 高濃縮洗碗碟機清潔劑","null","120","","PDT","","","");
insert into `t_items` value ("","TS0205","Concentrated Dishwasher Detergent","Top Shine 高濃縮洗碗碟機清潔劑","null","80","","PDT","","","");
insert into `t_items` value ("","TS0405","Concentrated Dishwasher Detergent","Top Shine 高濃縮洗碗碟機清潔劑","null","150","","PDT","","","");
insert into `t_items` value ("","TW0120","Chlorinated Sanitizer and Stain Remover","TW-11 氯性消毒除漬劑","null","52","","PDT","","","");
insert into `t_items` value ("","TW0205","Chlorinated Sanitizer and Stain Remover","TW-11 氯性消毒除漬劑","null","45","","PDT","","","");
insert into `t_items` value ("","TW0405","Chlorinated Sanitizer and Stain Remover","TW-11 氯性消毒除漬劑","null","86.88","","PDT","","","");
insert into `t_items` value ("","U20104","Urinal Drain Cleaner","U-2  生物廁盆尿石去除劑","null","270","","PDT","","","");
insert into `t_items` value ("","VC0120","Hydro Ventilator Hood Detergent","VC 運水煙罩化油劑","null","63","","PDT","","","");
insert into `t_items` value ("","VC0401","Hydro Ventilator Hood Detergent","VC 運水煙罩化油劑","null","90","","PDT","","","");
insert into `t_items` value ("","VC0405","Hydro Ventilator Hood Detergent","VC 運水煙罩化油劑","null","96","","PDT","","","");
insert into `t_items` value ("","VD0405","Hydro Vent Degreaser","運水煙罩化油劑","null","100","","PDT","","","");
insert into `t_items` value ("","CN-1","CANAAN CN-1 Door Type Dishwasher","CANAAN CN-1 揭門式洗碗碟機","null","13000","","PDT","","","");
insert into `t_items` value ("","CN-1E","CANAAN CN-1E Type Dishwasher","CANAAN CN-1E 揭門式洗碗碟機","null","13000","","PDT","","","");
insert into `t_items` value ("","CN-F","CANAAN Channel Type Dishwasher","CANAAN CN-F 通道式洗碗碟機","null","35000","","PDT","","","");
insert into `t_items` value ("","DR01","Plate Rack","洗碗碟機用針篩","null","60","","PDT","","","");
insert into `t_items` value ("","DR02","Open Rack","洗碗碟機用平篩 ","null","60","","PDT","","","");
insert into `t_items` value ("","DR03","Glass Rack","洗碗碟機用16格杯篩 ","null","0","","PDT","","","");
insert into `t_items` value ("","DR04","","8格刀叉籃","null","50","","PDT","","","");
insert into `t_items` value ("","DR05","","有柄杯篩車","null","150","","PDT","","","");
insert into `t_items` value ("","DR06","","洗碗碟機用25格杯篩 Glass Rack","null","0","","PDT","","","");
insert into `t_items` value ("","DR07","","杯機專用平篩 400x400x150mm","null","50","","PDT","","","");
insert into `t_items` value ("","DR08","","洗碗碟機用36格杯篩 Glass Rack","null","0","","PDT","","","");
insert into `t_items` value ("","DR09","","圓桶形刀叉籃","null","10","","PDT","","","");
insert into `t_items` value ("","GT-CR1","G-Tek GT-CR1 Conveyor Type Dishwasher","G-Tek GT-CR1 運輸帶式洗碗碟機 ","null","47600","","PDT","","","");
insert into `t_items` value ("","GT-D1","G-Tek GT-D1 Door Type Dishwasher","G-Tek GT-D1 揭門式單缸洗碗碟機Door type dishwasher","null","16500","","PDT","","","");
insert into `t_items` value ("","HSFD","Foam Type Hand Soap Dispenser","泡沬洗手皂液機 ","null","30","","PDT","","","");
insert into `t_items` value ("","SS-TABLE","Stainless Steel Table","不銹鋼檯","null","1000","","PDT","","","");
insert into `t_items` value ("","TS-603","Teikos TS-603 Under-Counter Dishwasher","Teikos TS-603  檯下式洗碗碟機","null","10000","","PDT","","","");
insert into `t_items` value ("","TS-830","Teikos TS-830 Under-Counter Glasswasher","Teikos TS-830  檯下式洗杯機","null","8000","","PDT","","","");
insert into `t_items` value ("","VCPUMP","","運水煙罩儀器","null","400","","PDT","","","");
insert into `t_items` value ("","Deposit","Deposit","洗碗碟機按金","null","0","","PDT","","","");
insert into `t_items` value ("","FL","Fly Light Rental Fee","捕蠅燈機租用月費","null","30","","PDT","","","");
insert into `t_items` value ("","R001","Diswasher Chemicals Monthly Fee","洗碗碟機清潔劑服務月費","null","0","","PDT","","","");
insert into `t_items` value ("","R002","Dishwasher Full Service Plan","洗碗碟機連清潔劑(全包)月費","null","0","","PDT","","","");
insert into `t_items` value ("","Rental","Diswasher Monthly Rental","洗碗碟機租用服務月費","null","0","","PDT","","","");
insert into `t_items` value ("","GWDP","","Glass Washer Drain Pipe","null","100","","PDT","","","");
insert into `t_items` value ("","Parts","Diswasher Parts","洗碗碟機零件","null","0","","PDT","","","");
insert into `t_items` value ("","CHVS","","油煙罩系統清潔服務","null","0","","PDT","","","");
insert into `t_items` value ("","CSS","","清洗蒸櫃服務連除垢劑","null","0","","PDT","","","");
insert into `t_items` value ("","JOB","","洗碗機及杯機裝拆費用","null","0","","PDT","","","");
insert into `t_items` value ("","P00001","Inspection Fee","洗碗碟機檢查費","null","0","","PDT","","","");